name: Continuous Integration
on:
  push:
    branches: '**'
    paths-ignore:
      - 'doc/**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches: '**'
    paths-ignore:
      - 'doc/**'

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19', '1.20' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run unit tests
        run: go test -race ./...
        working-directory: .

  integration:
    runs-on: ubuntu-latest
    services:
      postgres15:
        image: postgres:15
        env:
          POSTGRES_DB: cep
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run migrations
        run: psql -f migrations/schema.sql postgresql://postgres:secret@localhost:5432/cep?sslmode=disable
      - name: Run integration tests
        working-directory: storage/postgres
        run: go test -race -count=2 ./...
        env:
          TEST_DATABASE_URL: postgresql://postgres:secret@localhost:5432/cep?sslmode=disable

